/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message?: string;
}

export interface MessageResponse {
  message: string;
}

export interface LoginBody {
  email: string;
  password: string;
}

export interface RegisterBody {
  fullName: string;
  nationalId: string;
  phone: string;
  studyYear: string;
  email: string;
  password: string;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  admin: "admin",
  student: "student",
} as const;

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

export const UserStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  banned: "banned",
} as const;

export interface User {
  id: number;
  fullName: string;
  nationalId?: string;
  phone?: string;
  studyYear?: string;
  email: string;
  role: UserRole;
  status: UserStatus;
  createdAt: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

export type UpdateUserStatusBodyStatus =
  (typeof UpdateUserStatusBodyStatus)[keyof typeof UpdateUserStatusBodyStatus];

export const UpdateUserStatusBodyStatus = {
  approved: "approved",
  rejected: "rejected",
  banned: "banned",
} as const;

export interface UpdateUserStatusBody {
  status: UpdateUserStatusBodyStatus;
}

export interface UsersListResponse {
  users: User[];
  total: number;
  page?: number;
  limit?: number;
}

export interface UserStats {
  total: number;
  pending: number;
  approved: number;
  rejected: number;
  banned: number;
}

export interface Announcement {
  id: number;
  title: string;
  content: string;
  imageUrl?: string | null;
  createdAt: string;
}

export interface CreateAnnouncementBody {
  title: string;
  content: string;
  imageUrl?: string | null;
}

export type VideoSource = (typeof VideoSource)[keyof typeof VideoSource];

export const VideoSource = {
  youtube: "youtube",
  googledrive: "googledrive",
  mega: "mega",
} as const;

export interface Video {
  id: number;
  title: string;
  description?: string | null;
  url: string;
  source: VideoSource;
  courseId?: number | null;
  courseName?: string | null;
  createdAt: string;
}

export type CreateVideoBodySource =
  (typeof CreateVideoBodySource)[keyof typeof CreateVideoBodySource];

export const CreateVideoBodySource = {
  youtube: "youtube",
  googledrive: "googledrive",
  mega: "mega",
} as const;

export interface CreateVideoBody {
  title: string;
  description?: string | null;
  url: string;
  source: CreateVideoBodySource;
  courseId?: number | null;
}

export type PdfSource = (typeof PdfSource)[keyof typeof PdfSource];

export const PdfSource = {
  upload: "upload",
  mega: "mega",
  link: "link",
} as const;

export interface Pdf {
  id: number;
  title: string;
  description?: string | null;
  url: string;
  source: PdfSource;
  courseId?: number | null;
  courseName?: string | null;
  createdAt: string;
}

export type CreatePdfBodySource =
  (typeof CreatePdfBodySource)[keyof typeof CreatePdfBodySource];

export const CreatePdfBodySource = {
  upload: "upload",
  mega: "mega",
  link: "link",
} as const;

export interface CreatePdfBody {
  title: string;
  description?: string | null;
  url: string;
  source: CreatePdfBodySource;
  courseId?: number | null;
}

export interface Course {
  id: number;
  name: string;
  description?: string | null;
  duration?: string | null;
  schedule?: string | null;
  createdAt: string;
}

export interface CreateCourseBody {
  name: string;
  description?: string | null;
  duration?: string | null;
  schedule?: string | null;
}

export interface ContactInfo {
  about: string;
  phone?: string | null;
  email?: string | null;
  facebook?: string | null;
  telegram?: string | null;
  whatsapp?: string | null;
  instagram?: string | null;
}

export interface UpdateContactBody {
  about?: string;
  phone?: string | null;
  email?: string | null;
  facebook?: string | null;
  telegram?: string | null;
  whatsapp?: string | null;
  instagram?: string | null;
}

export interface UpdateBackgroundBody {
  backgroundUrl?: string | null;
  backgroundColor?: string | null;
}

export interface SiteSettings {
  backgroundUrl?: string | null;
  backgroundColor?: string | null;
}

export type ListUsersParams = {
  status?: ListUsersStatus;
  page?: number;
  limit?: number;
};

export type ListUsersStatus =
  (typeof ListUsersStatus)[keyof typeof ListUsersStatus];

export const ListUsersStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  banned: "banned",
} as const;

export type ListVideosParams = {
  courseId?: number;
};

export type ListPdfsParams = {
  courseId?: number;
};
