/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary User login
 */
export const LoginBody = zod.object({
  email: zod.string().email(),
  password: zod.string(),
});

export const LoginResponse = zod.object({
  token: zod.string(),
  user: zod.object({
    id: zod.number(),
    fullName: zod.string(),
    nationalId: zod.string().optional(),
    phone: zod.string().optional(),
    studyYear: zod.string().optional(),
    email: zod.string(),
    role: zod.enum(["admin", "student"]),
    status: zod.enum(["pending", "approved", "rejected", "banned"]),
    createdAt: zod.coerce.date(),
  }),
});

/**
 * @summary Register new user
 */
export const RegisterBody = zod.object({
  fullName: zod.string(),
  nationalId: zod.string(),
  phone: zod.string(),
  studyYear: zod.string(),
  email: zod.string().email(),
  password: zod.string(),
});

/**
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  fullName: zod.string(),
  nationalId: zod.string().optional(),
  phone: zod.string().optional(),
  studyYear: zod.string().optional(),
  email: zod.string(),
  role: zod.enum(["admin", "student"]),
  status: zod.enum(["pending", "approved", "rejected", "banned"]),
  createdAt: zod.coerce.date(),
});

/**
 * @summary List all users (admin only)
 */
export const ListUsersQueryParams = zod.object({
  status: zod.enum(["pending", "approved", "rejected", "banned"]).optional(),
  page: zod.coerce.number().optional(),
  limit: zod.coerce.number().optional(),
});

export const ListUsersResponse = zod.object({
  users: zod.array(
    zod.object({
      id: zod.number(),
      fullName: zod.string(),
      nationalId: zod.string().optional(),
      phone: zod.string().optional(),
      studyYear: zod.string().optional(),
      email: zod.string(),
      role: zod.enum(["admin", "student"]),
      status: zod.enum(["pending", "approved", "rejected", "banned"]),
      createdAt: zod.coerce.date(),
    }),
  ),
  total: zod.number(),
  page: zod.number().optional(),
  limit: zod.number().optional(),
});

/**
 * @summary Get user statistics (admin only)
 */
export const GetUserStatsResponse = zod.object({
  total: zod.number(),
  pending: zod.number(),
  approved: zod.number(),
  rejected: zod.number(),
  banned: zod.number(),
});

/**
 * @summary Get a user by ID (admin only)
 */
export const GetUserParams = zod.object({
  id: zod.coerce.number(),
});

export const GetUserResponse = zod.object({
  id: zod.number(),
  fullName: zod.string(),
  nationalId: zod.string().optional(),
  phone: zod.string().optional(),
  studyYear: zod.string().optional(),
  email: zod.string(),
  role: zod.enum(["admin", "student"]),
  status: zod.enum(["pending", "approved", "rejected", "banned"]),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update user status (admin only)
 */
export const UpdateUserStatusParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateUserStatusBody = zod.object({
  status: zod.enum(["approved", "rejected", "banned"]),
});

export const UpdateUserStatusResponse = zod.object({
  id: zod.number(),
  fullName: zod.string(),
  nationalId: zod.string().optional(),
  phone: zod.string().optional(),
  studyYear: zod.string().optional(),
  email: zod.string(),
  role: zod.enum(["admin", "student"]),
  status: zod.enum(["pending", "approved", "rejected", "banned"]),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a user (admin only)
 */
export const DeleteUserParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteUserResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary List all announcements
 */
export const ListAnnouncementsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  content: zod.string(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListAnnouncementsResponse = zod.array(
  ListAnnouncementsResponseItem,
);

/**
 * @summary Create an announcement (admin only)
 */
export const CreateAnnouncementBody = zod.object({
  title: zod.string(),
  content: zod.string(),
  imageUrl: zod.string().nullish(),
});

/**
 * @summary Delete an announcement (admin only)
 */
export const DeleteAnnouncementParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteAnnouncementResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary List all videos
 */
export const ListVideosQueryParams = zod.object({
  courseId: zod.coerce.number().optional(),
});

export const ListVideosResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string().nullish(),
  url: zod.string(),
  source: zod.enum(["youtube", "googledrive", "mega"]),
  courseId: zod.number().nullish(),
  courseName: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListVideosResponse = zod.array(ListVideosResponseItem);

/**
 * @summary Add a video (admin only)
 */
export const CreateVideoBody = zod.object({
  title: zod.string(),
  description: zod.string().nullish(),
  url: zod.string(),
  source: zod.enum(["youtube", "googledrive", "mega"]),
  courseId: zod.number().nullish(),
});

/**
 * @summary Delete a video (admin only)
 */
export const DeleteVideoParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteVideoResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary List all PDF files
 */
export const ListPdfsQueryParams = zod.object({
  courseId: zod.coerce.number().optional(),
});

export const ListPdfsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string().nullish(),
  url: zod.string(),
  source: zod.enum(["upload", "mega", "link"]),
  courseId: zod.number().nullish(),
  courseName: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListPdfsResponse = zod.array(ListPdfsResponseItem);

/**
 * @summary Add a PDF (admin only)
 */
export const CreatePdfBody = zod.object({
  title: zod.string(),
  description: zod.string().nullish(),
  url: zod.string(),
  source: zod.enum(["upload", "mega", "link"]),
  courseId: zod.number().nullish(),
});

/**
 * @summary Delete a PDF (admin only)
 */
export const DeletePdfParams = zod.object({
  id: zod.coerce.number(),
});

export const DeletePdfResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary List all courses
 */
export const ListCoursesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  duration: zod.string().nullish(),
  schedule: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListCoursesResponse = zod.array(ListCoursesResponseItem);

/**
 * @summary Create a course (admin only)
 */
export const CreateCourseBody = zod.object({
  name: zod.string(),
  description: zod.string().nullish(),
  duration: zod.string().nullish(),
  schedule: zod.string().nullish(),
});

/**
 * @summary Delete a course (admin only)
 */
export const DeleteCourseParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteCourseResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Get contact information
 */
export const GetContactResponse = zod.object({
  about: zod.string(),
  phone: zod.string().nullish(),
  email: zod.string().nullish(),
  facebook: zod.string().nullish(),
  telegram: zod.string().nullish(),
  whatsapp: zod.string().nullish(),
  instagram: zod.string().nullish(),
});

/**
 * @summary Update contact information (admin only)
 */
export const UpdateContactBody = zod.object({
  about: zod.string().optional(),
  phone: zod.string().nullish(),
  email: zod.string().nullish(),
  facebook: zod.string().nullish(),
  telegram: zod.string().nullish(),
  whatsapp: zod.string().nullish(),
  instagram: zod.string().nullish(),
});

export const UpdateContactResponse = zod.object({
  about: zod.string(),
  phone: zod.string().nullish(),
  email: zod.string().nullish(),
  facebook: zod.string().nullish(),
  telegram: zod.string().nullish(),
  whatsapp: zod.string().nullish(),
  instagram: zod.string().nullish(),
});

/**
 * @summary Update site background (admin only)
 */
export const UpdateBackgroundBody = zod.object({
  backgroundUrl: zod.string().nullish(),
  backgroundColor: zod.string().nullish(),
});

export const UpdateBackgroundResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Get site settings
 */
export const GetSettingsResponse = zod.object({
  backgroundUrl: zod.string().nullish(),
  backgroundColor: zod.string().nullish(),
});
