/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Announcement,
  AuthResponse,
  ContactInfo,
  Course,
  CreateAnnouncementBody,
  CreateCourseBody,
  CreatePdfBody,
  CreateVideoBody,
  ErrorResponse,
  HealthStatus,
  ListPdfsParams,
  ListUsersParams,
  ListVideosParams,
  LoginBody,
  MessageResponse,
  Pdf,
  RegisterBody,
  SiteSettings,
  UpdateBackgroundBody,
  UpdateContactBody,
  UpdateUserStatusBody,
  User,
  UserStats,
  UsersListResponse,
  Video,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary User login
 */
export const getLoginUrl = () => {
  return `/api/auth/login`;
};

export const login = async (
  loginBody: LoginBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginBody),
  });
};

export const getLoginMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: BodyType<LoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginBody>;
export type LoginMutationError = ErrorType<ErrorResponse>;

/**
 * @summary User login
 */
export const useLogin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  return useMutation(getLoginMutationOptions(options));
};

/**
 * @summary Register new user
 */
export const getRegisterUrl = () => {
  return `/api/auth/register`;
};

export const register = async (
  registerBody: RegisterBody,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerBody),
  });
};

export const getRegisterMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: BodyType<RegisterBody> }
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = BodyType<RegisterBody>;
export type RegisterMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register new user
 */
export const useRegister = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  return useMutation(getRegisterMutationOptions(options));
};

/**
 * @summary Get current user
 */
export const getGetMeUrl = () => {
  return `/api/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<User> => {
  return customFetch<User>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all users (admin only)
 */
export const getListUsersUrl = (params?: ListUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/users?${stringifiedParams}`
    : `/api/users`;
};

export const listUsers = async (
  params?: ListUsersParams,
  options?: RequestInit,
): Promise<UsersListResponse> => {
  return customFetch<UsersListResponse>(getListUsersUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListUsersQueryKey = (params?: ListUsersParams) => {
  return [`/api/users`, ...(params ? [params] : [])] as const;
};

export const getListUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listUsers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({
    signal,
  }) => listUsers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUsers>>
>;
export type ListUsersQueryError = ErrorType<unknown>;

/**
 * @summary List all users (admin only)
 */

export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listUsers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListUsersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user statistics (admin only)
 */
export const getGetUserStatsUrl = () => {
  return `/api/users/stats`;
};

export const getUserStats = async (
  options?: RequestInit,
): Promise<UserStats> => {
  return customFetch<UserStats>(getGetUserStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetUserStatsQueryKey = () => {
  return [`/api/users/stats`] as const;
};

export const getGetUserStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUserStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserStats>>> = ({
    signal,
  }) => getUserStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserStats>>
>;
export type GetUserStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get user statistics (admin only)
 */

export function useGetUserStats<
  TData = Awaited<ReturnType<typeof getUserStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUserStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a user by ID (admin only)
 */
export const getGetUserUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const getUser = async (
  id: number,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getGetUserUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetUserQueryKey = (id: number) => {
  return [`/api/users/${id}`] as const;
};

export const getGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({
    signal,
  }) => getUser(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUser>>
>;
export type GetUserQueryError = ErrorType<unknown>;

/**
 * @summary Get a user by ID (admin only)
 */

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update user status (admin only)
 */
export const getUpdateUserStatusUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const updateUserStatus = async (
  id: number,
  updateUserStatusBody: UpdateUserStatusBody,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getUpdateUserStatusUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserStatusBody),
  });
};

export const getUpdateUserStatusMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserStatus>>,
    TError,
    { id: number; data: BodyType<UpdateUserStatusBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserStatus>>,
  TError,
  { id: number; data: BodyType<UpdateUserStatusBody> },
  TContext
> => {
  const mutationKey = ["updateUserStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserStatus>>,
    { id: number; data: BodyType<UpdateUserStatusBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateUserStatus(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserStatus>>
>;
export type UpdateUserStatusMutationBody = BodyType<UpdateUserStatusBody>;
export type UpdateUserStatusMutationError = ErrorType<unknown>;

/**
 * @summary Update user status (admin only)
 */
export const useUpdateUserStatus = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserStatus>>,
    TError,
    { id: number; data: BodyType<UpdateUserStatusBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateUserStatus>>,
  TError,
  { id: number; data: BodyType<UpdateUserStatusBody> },
  TContext
> => {
  return useMutation(getUpdateUserStatusMutationOptions(options));
};

/**
 * @summary Delete a user (admin only)
 */
export const getDeleteUserUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const deleteUser = async (
  id: number,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getDeleteUserUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUser>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUser(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>;

export type DeleteUserMutationError = ErrorType<unknown>;

/**
 * @summary Delete a user (admin only)
 */
export const useDeleteUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteUserMutationOptions(options));
};

/**
 * @summary List all announcements
 */
export const getListAnnouncementsUrl = () => {
  return `/api/announcements`;
};

export const listAnnouncements = async (
  options?: RequestInit,
): Promise<Announcement[]> => {
  return customFetch<Announcement[]>(getListAnnouncementsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAnnouncementsQueryKey = () => {
  return [`/api/announcements`] as const;
};

export const getListAnnouncementsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAnnouncements>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAnnouncements>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAnnouncementsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAnnouncements>>
  > = ({ signal }) => listAnnouncements({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAnnouncements>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAnnouncementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAnnouncements>>
>;
export type ListAnnouncementsQueryError = ErrorType<unknown>;

/**
 * @summary List all announcements
 */

export function useListAnnouncements<
  TData = Awaited<ReturnType<typeof listAnnouncements>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAnnouncements>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAnnouncementsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create an announcement (admin only)
 */
export const getCreateAnnouncementUrl = () => {
  return `/api/announcements`;
};

export const createAnnouncement = async (
  createAnnouncementBody: CreateAnnouncementBody,
  options?: RequestInit,
): Promise<Announcement> => {
  return customFetch<Announcement>(getCreateAnnouncementUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAnnouncementBody),
  });
};

export const getCreateAnnouncementMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAnnouncement>>,
    TError,
    { data: BodyType<CreateAnnouncementBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAnnouncement>>,
  TError,
  { data: BodyType<CreateAnnouncementBody> },
  TContext
> => {
  const mutationKey = ["createAnnouncement"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAnnouncement>>,
    { data: BodyType<CreateAnnouncementBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createAnnouncement(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAnnouncementMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAnnouncement>>
>;
export type CreateAnnouncementMutationBody = BodyType<CreateAnnouncementBody>;
export type CreateAnnouncementMutationError = ErrorType<unknown>;

/**
 * @summary Create an announcement (admin only)
 */
export const useCreateAnnouncement = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAnnouncement>>,
    TError,
    { data: BodyType<CreateAnnouncementBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createAnnouncement>>,
  TError,
  { data: BodyType<CreateAnnouncementBody> },
  TContext
> => {
  return useMutation(getCreateAnnouncementMutationOptions(options));
};

/**
 * @summary Delete an announcement (admin only)
 */
export const getDeleteAnnouncementUrl = (id: number) => {
  return `/api/announcements/${id}`;
};

export const deleteAnnouncement = async (
  id: number,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getDeleteAnnouncementUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAnnouncementMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAnnouncement>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAnnouncement>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAnnouncement"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAnnouncement>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAnnouncement(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAnnouncementMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAnnouncement>>
>;

export type DeleteAnnouncementMutationError = ErrorType<unknown>;

/**
 * @summary Delete an announcement (admin only)
 */
export const useDeleteAnnouncement = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAnnouncement>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteAnnouncement>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteAnnouncementMutationOptions(options));
};

/**
 * @summary List all videos
 */
export const getListVideosUrl = (params?: ListVideosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/videos?${stringifiedParams}`
    : `/api/videos`;
};

export const listVideos = async (
  params?: ListVideosParams,
  options?: RequestInit,
): Promise<Video[]> => {
  return customFetch<Video[]>(getListVideosUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListVideosQueryKey = (params?: ListVideosParams) => {
  return [`/api/videos`, ...(params ? [params] : [])] as const;
};

export const getListVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: ListVideosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listVideos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listVideos>>> = ({
    signal,
  }) => listVideos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listVideos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVideos>>
>;
export type ListVideosQueryError = ErrorType<unknown>;

/**
 * @summary List all videos
 */

export function useListVideos<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: ListVideosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listVideos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListVideosQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a video (admin only)
 */
export const getCreateVideoUrl = () => {
  return `/api/videos`;
};

export const createVideo = async (
  createVideoBody: CreateVideoBody,
  options?: RequestInit,
): Promise<Video> => {
  return customFetch<Video>(getCreateVideoUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createVideoBody),
  });
};

export const getCreateVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVideo>>,
    TError,
    { data: BodyType<CreateVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createVideo>>,
  TError,
  { data: BodyType<CreateVideoBody> },
  TContext
> => {
  const mutationKey = ["createVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createVideo>>,
    { data: BodyType<CreateVideoBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createVideo(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof createVideo>>
>;
export type CreateVideoMutationBody = BodyType<CreateVideoBody>;
export type CreateVideoMutationError = ErrorType<unknown>;

/**
 * @summary Add a video (admin only)
 */
export const useCreateVideo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVideo>>,
    TError,
    { data: BodyType<CreateVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createVideo>>,
  TError,
  { data: BodyType<CreateVideoBody> },
  TContext
> => {
  return useMutation(getCreateVideoMutationOptions(options));
};

/**
 * @summary Delete a video (admin only)
 */
export const getDeleteVideoUrl = (id: number) => {
  return `/api/videos/${id}`;
};

export const deleteVideo = async (
  id: number,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getDeleteVideoUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVideo>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVideo>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteVideo(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVideo>>
>;

export type DeleteVideoMutationError = ErrorType<unknown>;

/**
 * @summary Delete a video (admin only)
 */
export const useDeleteVideo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVideo>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteVideoMutationOptions(options));
};

/**
 * @summary List all PDF files
 */
export const getListPdfsUrl = (params?: ListPdfsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/pdfs?${stringifiedParams}`
    : `/api/pdfs`;
};

export const listPdfs = async (
  params?: ListPdfsParams,
  options?: RequestInit,
): Promise<Pdf[]> => {
  return customFetch<Pdf[]>(getListPdfsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListPdfsQueryKey = (params?: ListPdfsParams) => {
  return [`/api/pdfs`, ...(params ? [params] : [])] as const;
};

export const getListPdfsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPdfs>>,
  TError = ErrorType<unknown>,
>(
  params?: ListPdfsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listPdfs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPdfsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPdfs>>> = ({
    signal,
  }) => listPdfs(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPdfs>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListPdfsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPdfs>>
>;
export type ListPdfsQueryError = ErrorType<unknown>;

/**
 * @summary List all PDF files
 */

export function useListPdfs<
  TData = Awaited<ReturnType<typeof listPdfs>>,
  TError = ErrorType<unknown>,
>(
  params?: ListPdfsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listPdfs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListPdfsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a PDF (admin only)
 */
export const getCreatePdfUrl = () => {
  return `/api/pdfs`;
};

export const createPdf = async (
  createPdfBody: CreatePdfBody,
  options?: RequestInit,
): Promise<Pdf> => {
  return customFetch<Pdf>(getCreatePdfUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPdfBody),
  });
};

export const getCreatePdfMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPdf>>,
    TError,
    { data: BodyType<CreatePdfBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPdf>>,
  TError,
  { data: BodyType<CreatePdfBody> },
  TContext
> => {
  const mutationKey = ["createPdf"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPdf>>,
    { data: BodyType<CreatePdfBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createPdf(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePdfMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPdf>>
>;
export type CreatePdfMutationBody = BodyType<CreatePdfBody>;
export type CreatePdfMutationError = ErrorType<unknown>;

/**
 * @summary Add a PDF (admin only)
 */
export const useCreatePdf = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPdf>>,
    TError,
    { data: BodyType<CreatePdfBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createPdf>>,
  TError,
  { data: BodyType<CreatePdfBody> },
  TContext
> => {
  return useMutation(getCreatePdfMutationOptions(options));
};

/**
 * @summary Delete a PDF (admin only)
 */
export const getDeletePdfUrl = (id: number) => {
  return `/api/pdfs/${id}`;
};

export const deletePdf = async (
  id: number,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getDeletePdfUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeletePdfMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePdf>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePdf>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deletePdf"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePdf>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deletePdf(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePdfMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePdf>>
>;

export type DeletePdfMutationError = ErrorType<unknown>;

/**
 * @summary Delete a PDF (admin only)
 */
export const useDeletePdf = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePdf>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deletePdf>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeletePdfMutationOptions(options));
};

/**
 * @summary List all courses
 */
export const getListCoursesUrl = () => {
  return `/api/courses`;
};

export const listCourses = async (options?: RequestInit): Promise<Course[]> => {
  return customFetch<Course[]>(getListCoursesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListCoursesQueryKey = () => {
  return [`/api/courses`] as const;
};

export const getListCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof listCourses>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCourses>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCourses>>> = ({
    signal,
  }) => listCourses({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCourses>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCoursesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCourses>>
>;
export type ListCoursesQueryError = ErrorType<unknown>;

/**
 * @summary List all courses
 */

export function useListCourses<
  TData = Awaited<ReturnType<typeof listCourses>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCourses>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCoursesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a course (admin only)
 */
export const getCreateCourseUrl = () => {
  return `/api/courses`;
};

export const createCourse = async (
  createCourseBody: CreateCourseBody,
  options?: RequestInit,
): Promise<Course> => {
  return customFetch<Course>(getCreateCourseUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCourseBody),
  });
};

export const getCreateCourseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCourse>>,
    TError,
    { data: BodyType<CreateCourseBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: BodyType<CreateCourseBody> },
  TContext
> => {
  const mutationKey = ["createCourse"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCourse>>,
    { data: BodyType<CreateCourseBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createCourse(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCourseMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCourse>>
>;
export type CreateCourseMutationBody = BodyType<CreateCourseBody>;
export type CreateCourseMutationError = ErrorType<unknown>;

/**
 * @summary Create a course (admin only)
 */
export const useCreateCourse = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCourse>>,
    TError,
    { data: BodyType<CreateCourseBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: BodyType<CreateCourseBody> },
  TContext
> => {
  return useMutation(getCreateCourseMutationOptions(options));
};

/**
 * @summary Delete a course (admin only)
 */
export const getDeleteCourseUrl = (id: number) => {
  return `/api/courses/${id}`;
};

export const deleteCourse = async (
  id: number,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getDeleteCourseUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCourseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCourse>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCourse"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCourse>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCourse(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCourseMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCourse>>
>;

export type DeleteCourseMutationError = ErrorType<unknown>;

/**
 * @summary Delete a course (admin only)
 */
export const useDeleteCourse = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCourse>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteCourseMutationOptions(options));
};

/**
 * @summary Get contact information
 */
export const getGetContactUrl = () => {
  return `/api/contact`;
};

export const getContact = async (
  options?: RequestInit,
): Promise<ContactInfo> => {
  return customFetch<ContactInfo>(getGetContactUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetContactQueryKey = () => {
  return [`/api/contact`] as const;
};

export const getGetContactQueryOptions = <
  TData = Awaited<ReturnType<typeof getContact>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getContact>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetContactQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getContact>>> = ({
    signal,
  }) => getContact({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getContact>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetContactQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContact>>
>;
export type GetContactQueryError = ErrorType<unknown>;

/**
 * @summary Get contact information
 */

export function useGetContact<
  TData = Awaited<ReturnType<typeof getContact>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getContact>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetContactQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update contact information (admin only)
 */
export const getUpdateContactUrl = () => {
  return `/api/contact`;
};

export const updateContact = async (
  updateContactBody: UpdateContactBody,
  options?: RequestInit,
): Promise<ContactInfo> => {
  return customFetch<ContactInfo>(getUpdateContactUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateContactBody),
  });
};

export const getUpdateContactMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateContact>>,
    TError,
    { data: BodyType<UpdateContactBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateContact>>,
  TError,
  { data: BodyType<UpdateContactBody> },
  TContext
> => {
  const mutationKey = ["updateContact"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateContact>>,
    { data: BodyType<UpdateContactBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateContact(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateContactMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateContact>>
>;
export type UpdateContactMutationBody = BodyType<UpdateContactBody>;
export type UpdateContactMutationError = ErrorType<unknown>;

/**
 * @summary Update contact information (admin only)
 */
export const useUpdateContact = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateContact>>,
    TError,
    { data: BodyType<UpdateContactBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateContact>>,
  TError,
  { data: BodyType<UpdateContactBody> },
  TContext
> => {
  return useMutation(getUpdateContactMutationOptions(options));
};

/**
 * @summary Update site background (admin only)
 */
export const getUpdateBackgroundUrl = () => {
  return `/api/settings/background`;
};

export const updateBackground = async (
  updateBackgroundBody: UpdateBackgroundBody,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getUpdateBackgroundUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateBackgroundBody),
  });
};

export const getUpdateBackgroundMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBackground>>,
    TError,
    { data: BodyType<UpdateBackgroundBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBackground>>,
  TError,
  { data: BodyType<UpdateBackgroundBody> },
  TContext
> => {
  const mutationKey = ["updateBackground"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBackground>>,
    { data: BodyType<UpdateBackgroundBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateBackground(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBackgroundMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateBackground>>
>;
export type UpdateBackgroundMutationBody = BodyType<UpdateBackgroundBody>;
export type UpdateBackgroundMutationError = ErrorType<unknown>;

/**
 * @summary Update site background (admin only)
 */
export const useUpdateBackground = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBackground>>,
    TError,
    { data: BodyType<UpdateBackgroundBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateBackground>>,
  TError,
  { data: BodyType<UpdateBackgroundBody> },
  TContext
> => {
  return useMutation(getUpdateBackgroundMutationOptions(options));
};

/**
 * @summary Get site settings
 */
export const getGetSettingsUrl = () => {
  return `/api/settings`;
};

export const getSettings = async (
  options?: RequestInit,
): Promise<SiteSettings> => {
  return customFetch<SiteSettings>(getGetSettingsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSettingsQueryKey = () => {
  return [`/api/settings`] as const;
};

export const getGetSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettings>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSettings>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({
    signal,
  }) => getSettings({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettings>>
>;
export type GetSettingsQueryError = ErrorType<unknown>;

/**
 * @summary Get site settings
 */

export function useGetSettings<
  TData = Awaited<ReturnType<typeof getSettings>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSettings>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSettingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
