/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateVideoBodySource } from "./createVideoBodySource";

export interface CreateVideoBody {
  title: string;
  description?: string | null;
  url: string;
  source: CreateVideoBodySource;
  courseId?: number | null;
}
