/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */

export * from "./announcement";
export * from "./authResponse";
export * from "./contactInfo";
export * from "./course";
export * from "./createAnnouncementBody";
export * from "./createCourseBody";
export * from "./createPdfBody";
export * from "./createPdfBodySource";
export * from "./createVideoBody";
export * from "./createVideoBodySource";
export * from "./errorResponse";
export * from "./healthStatus";
export * from "./listPdfsParams";
export * from "./listUsersParams";
export * from "./listUsersStatus";
export * from "./listVideosParams";
export * from "./loginBody";
export * from "./messageResponse";
export * from "./pdf";
export * from "./pdfSource";
export * from "./registerBody";
export * from "./siteSettings";
export * from "./updateBackgroundBody";
export * from "./updateContactBody";
export * from "./updateUserStatusBody";
export * from "./updateUserStatusBodyStatus";
export * from "./user";
export * from "./userRole";
export * from "./usersListResponse";
export * from "./userStats";
export * from "./userStatus";
export * from "./video";
export * from "./videoSource";
