/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { PdfSource } from "./pdfSource";

export interface Pdf {
  id: number;
  title: string;
  description?: string | null;
  url: string;
  source: PdfSource;
  courseId?: number | null;
  courseName?: string | null;
  createdAt: Date;
}
