/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */

export type PdfSource = (typeof PdfSource)[keyof typeof PdfSource];

export const PdfSource = {
  upload: "upload",
  mega: "mega",
  link: "link",
} as const;
