/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */

export type UpdateUserStatusBodyStatus =
  (typeof UpdateUserStatusBodyStatus)[keyof typeof UpdateUserStatusBodyStatus];

export const UpdateUserStatusBodyStatus = {
  approved: "approved",
  rejected: "rejected",
  banned: "banned",
} as const;
