/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  admin: "admin",
  student: "student",
} as const;
