/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from "./userRole";
import type { UserStatus } from "./userStatus";

export interface User {
  id: number;
  fullName: string;
  nationalId?: string;
  phone?: string;
  studyYear?: string;
  email: string;
  role: UserRole;
  status: UserStatus;
  createdAt: Date;
}
