/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * منصة الدكتور علي سعد - Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoSource } from "./videoSource";

export interface Video {
  id: number;
  title: string;
  description?: string | null;
  url: string;
  source: VideoSource;
  courseId?: number | null;
  courseName?: string | null;
  createdAt: Date;
}
